### ISSUE TITLE
Permanent storage

### ISSUE THREAD

**Issue by bibby** [Leo675/twitch-botbuster#3]
Banned users remain in twitch, but whitelisted users reside in memory, and would be lost on a bot restart. Please consider adding a permanent storage mechanism.

Fast cheap and easy would be `peewee` with `sqlite`, if I were to recommend.

**Comment by IDSninja** [comment]
I like this idea and I will work towards implementing permanent storage. I'll leave this open until it's implemented.

**Comment by Leo675** [comment]
Completed

Used sqlite3 to store whitelisted and permanently banned users
