### ISSUE TITLE
requirements file

### ISSUE THREAD

**Issue by bibby** [Leo675/twitch-botbuster#6]
You may want to include a [requirements file](https://pip.readthedocs.io/en/1.1/requirements.html), for easier installation by docker or [virtualenv](http://docs.python-guide.org/en/latest/dev/virtualenvs/).

Right now, the only item to add is `requests`, but I have the sense there will be more.

**Comment by Leo675** [comment]
Completed.

Used the native sqlite3 module so requests is still the only nonstandard module.
